name: Delete Untagged Container Versions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  delete-container-versions:
    uses: ./.github/workflows/delete-container-versions.yml
    with:
      package_name: 'service-detection'
      package_type: 'container'